spring:
  datasource:
    url: jdbc:mysql://db-arie-financial-mysql.cnsjmaowunhf.us-west-2.rds.amazonaws.com:3306/Arie_Loans
    username: arieAdmin
    password: Arie123Loans
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true




